In [1]:
import pandas as pd

In [2]:
df1=pd.read_csv('C:/Users/dell/Desktop/Selected Topics Project/fake_job_postings.csv')
df1.head()

job_id                                      title            location  \
0       1                           Marketing Intern    US, NY, New York   
1       2  Customer Service - Cloud Video Production      NZ, , Auckland   
2       3    Commissioning Machinery Assistant (CMA)       US, IA, Wever   
3       4          Account Executive - Washington DC  US, DC, Washington   
4       5                        Bill Review Manager  US, FL, Fort Worth   

  department salary_range                                    company_profile  \
0  Marketing          NaN  We're Food52, and we've created a groundbreaki...   
1    Success          NaN  90 Seconds, the worlds Cloud Video Production ...   
2        NaN          NaN  Valor Services provides Workforce Solutions th...   
3      Sales          NaN  Our passion for improving quality of life thro...   
4        NaN          NaN  SpotSource Solutions LLC is a Global Human Cap...   

                                         description  \
0  Food52, a fast-growing, James Beard Award-winn...   
1  Organised - Focused - Vibrant - Awesome!Do you...   
2  Our client, located in Houston, is actively se...   
3  THE COMPANY: ESRI – Environmental Systems Rese...   
4  JOB TITLE: Itemization Review ManagerLOCATION:...   

                                        requirements  \
0  Experience with content management systems a m...   
1  What we expect from you:Your key responsibilit...   
2  Implement pre-commissioning and commissioning ...   
3  EDUCATION: Bachelor’s or Master’s in GIS, busi...   
4  QUALIFICATIONS:RN license in the State of Texa...   

                                            benefits  telecommuting  \
0                                                NaN              0   
1  What you will get from usThrough being part of...              0   
2                                                NaN              0   
3  Our culture is anything but corporate—we have ...              0   
4                              Full Benefits Offered              0   

   has_company_logo  has_questions employment_type required_experience  \
0                 1              0           Other          Internship   
1                 1              0       Full-time      Not Applicable   
2                 1              0             NaN                 NaN   
3                 1              0       Full-time    Mid-Senior level   
4                 1              1       Full-time    Mid-Senior level   

  required_education                   industry              function  \
0                NaN                        NaN             Marketing   
1                NaN  Marketing and Advertising      Customer Service   
2                NaN                        NaN                   NaN   
3  Bachelor's Degree          Computer Software                 Sales   
4  Bachelor's Degree     Hospital & Health Care  Health Care Provider   

   fraudulent  
0           0  
1           0  
2           0  
3           0  
4           0

In [3]:
df1.shape

(17880, 18)

In [4]:
df=df1[['description','requirements','fraudulent']]
df.head()

description  \
0  Food52, a fast-growing, James Beard Award-winn...   
1  Organised - Focused - Vibrant - Awesome!Do you...   
2  Our client, located in Houston, is actively se...   
3  THE COMPANY: ESRI – Environmental Systems Rese...   
4  JOB TITLE: Itemization Review ManagerLOCATION:...   

                                        requirements  fraudulent  
0  Experience with content management systems a m...           0  
1  What we expect from you:Your key responsibilit...           0  
2  Implement pre-commissioning and commissioning ...           0  
3  EDUCATION: Bachelor’s or Master’s in GIS, busi...           0  
4  QUALIFICATIONS:RN license in the State of Texa...           0

In [5]:
###Drop Nan Values
df=df.dropna()

In [6]:
df.shape

(15185, 3)

In [7]:
## Get the Independent Features

X=df.drop('fraudulent',axis=1)

In [8]:
## Get the Dependent features
y=df['fraudulent']

In [9]:
y.value_counts()

0    14473
1      712
Name: fraudulent, dtype: int64

In [10]:
import tensorflow as tf
tf.__version__

'2.7.0'

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Bidirectional
from tensorflow.keras.layers import Dropout

In [12]:
voc_size=5000

In [13]:
message = X.copy()

In [14]:
message['description'][1]

"Organised - Focused - Vibrant - Awesome!Do you have a passion for customer service? Slick typing skills? Maybe Account Management? ...And think administration is cooler than a polar bear on a jetski? Then we need to hear you!\xa0We are the Cloud Video Production Service and opperating on a glodal level. Yeah, it's pretty cool. Serious about\xa0delivering a world class product and excellent customer service.Our rapidly expanding business is looking for a talented Project Manager to manage the successful delivery of video projects, manage client communications and drive the production process. Work with some of the coolest brands on the planet and learn from a global team that are representing NZ is a huge way!We are entering the next growth stage of our business and growing quickly internationally. \xa0Therefore, the position is bursting with opportunity for the right person entering the business at the right time.\xa090 Seconds, the worlds Cloud Video Production Service -\xa0http://90

In [15]:
message.reset_index(inplace=True)

In [16]:
import nltk
import re
from nltk.corpus import stopwords

In [17]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(message)):
    review = re.sub('[^a-zA-Z]', ' ', message['description'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

In [18]:
corpus[1]

'organis focus vibrant awesom passion custom servic slick type skill mayb account manag think administr cooler polar bear jetski need hear cloud video product servic opper glodal level yeah pretti cool seriou deliv world class product excel custom servic rapidli expand busi look talent project manag manag success deliveri video project manag client commun drive product process work coolest brand planet learn global team repres nz huge way enter next growth stage busi grow quickli intern therefor posit burst opportun right person enter busi right time second world cloud video product servic http url fbe afac cd c f b eef e e f ca dd second world cloud video product servic enabl brand agenc get high qualiti onlin video content shot produc anywher world fast afford manag seamlessli cloud purchas publish second remov hassl cost risk speed issu work regular video product compani manag everi aspect video project beauti onlin experi grow network rate video profession countri dedic product suc

In [19]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr[1]

[827,
 4978,
 324,
 4658,
 250,
 2044,
 1287,
 951,
 2610,
 36,
 3029,
 32,
 2329,
 3778,
 3306,
 70,
 1293,
 4618,
 3915,
 2286,
 4348,
 947,
 2792,
 1881,
 1287,
 2789,
 4062,
 2794,
 3475,
 3731,
 2292,
 3921,
 2310,
 569,
 14,
 1881,
 1965,
 2044,
 1287,
 4237,
 652,
 623,
 608,
 1479,
 3190,
 2329,
 2329,
 1763,
 579,
 2792,
 3190,
 2329,
 469,
 3830,
 255,
 1881,
 58,
 424,
 3412,
 1267,
 2012,
 1280,
 1897,
 3943,
 406,
 4003,
 2373,
 800,
 39,
 4172,
 4088,
 2760,
 623,
 1914,
 997,
 2352,
 834,
 178,
 4283,
 58,
 3919,
 4930,
 39,
 623,
 3919,
 903,
 3501,
 569,
 947,
 2792,
 1881,
 1287,
 3244,
 752,
 3184,
 4326,
 2988,
 2753,
 1426,
 3330,
 774,
 2358,
 2358,
 1426,
 4584,
 3027,
 3501,
 569,
 947,
 2792,
 1881,
 1287,
 868,
 1267,
 685,
 3617,
 1144,
 3195,
 1360,
 2792,
 3837,
 4268,
 4155,
 435,
 569,
 1724,
 3158,
 2329,
 82,
 947,
 301,
 1271,
 3501,
 3105,
 839,
 550,
 2446,
 4004,
 3380,
 424,
 3625,
 2792,
 1881,
 359,
 2329,
 3089,
 750,
 2792,
 3190,
 2874,
 1360,

In [20]:
sent_length=40
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[4417 3837 2329 ... 3405 1405 4655]
 [1763 1950  726 ...  653 3022 2028]
 [   0    0    0 ... 2089  545 4343]
 ...
 [3807 4544 3890 ... 4180   84 4336]
 [1962 1379 1034 ...  496 2352 3190]
 [ 876 2209 1938 ... 4592 4681  678]]


In [21]:
embedded_docs[0]

array([4417, 3837, 2329,  961, 4465, 4434, 2743, 4494, 2483, 1004, 1762,
       1762, 2483, 2950, 2818, 2541, 2483, 4784, 2483, 3637, 3882,  106,
       2269, 3122, 1469, 3306,  424, 4396,  732,  249, 1540,  293, 3379,
       2283, 1087, 1441, 2126, 3405, 1405, 4655])

In [22]:
## Creating model
embedding_vector_features=50
model1=Sequential()
model1.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model1.add(LSTM(100)) ##Just add bidirectional!!, except it would just behave as normal LSTM Model
model1.add(Dropout(0.3))
model1.add(Dense(1,activation='sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model1.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 40, 50)            250000    
                                                                 
 lstm (LSTM)                 (None, 100)               60400     
                                                                 
 dropout (Dropout)           (None, 100)               0         
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 310,501
Trainable params: 310,501
Non-trainable params: 0
_________________________________________________________________
None


In [23]:
len(embedded_docs),y.shape

(15185, (15185,))

In [24]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [25]:
X_final[1]

array([1763, 1950,  726, 1564, 4179, 3035, 3642, 3501, 4155,  708, 2792,
       4407, 1897, 1267, 2300,  569, 3800, 2300, 4708,  726, 1499,  260,
       2848, 1469, 3209,  949, 1176,  203,  106, 1843, 3209, 1469, 3707,
       3919, 1179, 2085,  890,  653, 3022, 2028])

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.25, random_state=32)

In [27]:
model1.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=12,batch_size=64)

Epoch 1/12
178/178 [==============================] - 7s 33ms/step - loss: 0.1992 - accuracy: 0.9546 - val_loss: 0.1612 - val_accuracy: 0.9568
Epoch 2/12
178/178 [==============================] - 5s 30ms/step - loss: 0.0922 - accuracy: 0.9738 - val_loss: 0.1659 - val_accuracy: 0.9594
Epoch 3/12
178/178 [==============================] - 5s 31ms/step - loss: 0.0580 - accuracy: 0.9831 - val_loss: 0.1345 - val_accuracy: 0.9644
Epoch 4/12
178/178 [==============================] - 6s 31ms/step - loss: 0.0418 - accuracy: 0.9887 - val_loss: 0.1552 - val_accuracy: 0.9652
Epoch 5/12
178/178 [==============================] - 6s 32ms/step - loss: 0.0273 - accuracy: 0.9925 - val_loss: 0.1708 - val_accuracy: 0.9639
Epoch 6/12
178/178 [==============================] - 6s 33ms/step - loss: 0.0197 - accuracy: 0.9946 - val_loss: 0.1640 - val_accuracy: 0.9565
Epoch 7/12
178/178 [==============================] - 6s 33ms/step - loss: 0.0137 - accuracy: 0.9954 - val_loss: 0.1916 - val_accuracy: 0.9658

In [28]:
y_pred=model1.predict(X_test)

In [29]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred.round())

array([[3537,   48],
       [ 103,  109]], dtype=int64)

In [30]:
from sklearn.metrics import accuracy_score
print('accuracy : ', accuracy_score(y_test,y_pred.round()) * 100, '%')

accuracy :  96.02317619173031 %


In [31]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred.round()))

              precision    recall  f1-score   support

           0       0.97      0.99      0.98      3585
           1       0.69      0.51      0.59       212

    accuracy                           0.96      3797
   macro avg       0.83      0.75      0.78      3797
weighted avg       0.96      0.96      0.96      3797

